In [15]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier


#Dataset PATH
dataset_PATH = "CW2_Datasets/dataset1.csv"
DataFrame = pd.read_csv(dataset_PATH)

print("Dataset shape:", DataFrame.shape)
print("\nMissing values:\n", DataFrame.isnull().sum())


X = DataFrame.drop(columns=["id", "level"])
severity_Label = DataFrame["level"].astype(int)
presence_Label = (severity_Label > 0).astype(int)


#Preprocessing
categorical_features = X.select_dtypes(include="object").columns
numerical_features = X.select_dtypes(exclude="object").columns

X[numerical_features] = X[numerical_features].fillna(X[numerical_features].mean())

for i in categorical_features:
    X[i] = X[i].fillna(X[i].mode()[0])

X = pd.get_dummies(X, columns=categorical_features, drop_first=False)

X = X.values.astype(np.float32)
presence_Label = presence_Label.values
severity_Label = severity_Label.values


X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X, presence_Label, test_size=0.2, random_state=42, stratify=presence_Label
)

X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(
    X, severity_Label, test_size=0.2, random_state=42, stratify=severity_Label
)


def Model_Evaluation(title, y_true, y_pred, target_names=None):
    print("\n------------------------------")
    print("Model:", title)
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_true, y_pred))
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=target_names, zero_division=0))


#Using 3 models for comparison
models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Naive Bayes": GaussianNB(),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
}



print("\n[Binary Classification (0 vs >0)]")
for name, clf in models.items():
    clf.fit(X_train_b, y_train_b)
    preds = clf.predict(X_test_b)
    Model_Evaluation(name, y_test_b, preds, target_names=["No disease", "Disease"])



print("\n[Multiclass Classification (0 to 4)]")
for name, clf in models.items():
    clf.fit(X_train_m, y_train_m)
    preds = clf.predict(X_test_m)
    Model_Evaluation(name, y_test_m, preds)


Dataset shape: (920, 16)

Missing values:
 id            0
age           0
sex           0
Origin        0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
level         0
dtype: int64

[Binary Classification (0 vs >0)]

------------------------------
Model: Decision Tree
Accuracy: 0.7771739130434783

Confusion Matrix:
[[58 24]
 [17 85]]

Classification Report:
              precision    recall  f1-score   support

  No disease       0.77      0.71      0.74        82
     Disease       0.78      0.83      0.81       102

    accuracy                           0.78       184
   macro avg       0.78      0.77      0.77       184
weighted avg       0.78      0.78      0.78       184


------------------------------
Model: Naive Bayes
Accuracy: 0.875

Confusion Matrix:
[[69 13]
 [10 92]]

Classification Report:
              precision    recall  f1-score   support

C:\Users\rohan\AppData\Local\Temp\ipykernel_105524\1369205083.py:32: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[i] = X[i].fillna(X[i].mode()[0])



------------------------------
Model: Random Forest
Accuracy: 0.842391304347826

Confusion Matrix:
[[65 17]
 [12 90]]

Classification Report:
              precision    recall  f1-score   support

  No disease       0.84      0.79      0.82        82
     Disease       0.84      0.88      0.86       102

    accuracy                           0.84       184
   macro avg       0.84      0.84      0.84       184
weighted avg       0.84      0.84      0.84       184


[Multiclass Classification (0 to 4)]

------------------------------
Model: Decision Tree
Accuracy: 0.5054347826086957

Confusion Matrix:
[[54 17  5  4  2]
 [15 27  7  3  1]
 [ 3  7  7  5  0]
 [ 4  6  6  5  0]
 [ 1  1  2  2  0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.66      0.68        82
           1       0.47      0.51      0.49        53
           2       0.26      0.32      0.29        22
           3       0.26      0.24      0.25        21
     